[workspace]

members = [
    "common",
    # "barretenberg_js",
    "barretenberg_wasm",
    # "aztec_backend_wasm",
]
# This has compilation problems on most platforms
exclude = ["barretenberg_static_lib"]
